server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: cards
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"

build:
  version: 3.0.2

cards:
  message: "Welcome to FinVista Nexus Bank's Cards related dev APIs "
  contactDetails:
    name: "Avery Blaze - Tech Wizard"
    email: "avery@finvistanexus.com"
  onCallSupport:
    - (555) 765-4321
    - (555) 876-5432