server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: loans
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"

build:
  version: 3.4.1

loans:
  message: "Welcome to FinVista Nexus Bank's Loans related dev APIs "
  contactDetails:
    name: "River Knight - Backend Specialist"
    email: "river@finvistanexus.com"
  onCallSupport:
    - (555) 321-0987
    - (555) 210-9876