server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: accounts
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
#  profiles:
#    active:
#      - "qa"

build:
  version: 3.0.0

accounts:
  message: "Welcome to FinVista Nexus Bank's Accounts related dev APIs "
  contactDetails:
    name: "Alex Nightshade - Developer"
    email: "alex@finvistanexus.com"
  onCallSupport:
    - (555) 666-7890
    - (555) 777-8901