version: '3.9'

services:
  accounts-db:
    image: mysql
    container_name: fvn-accounts-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accounts-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  loans-db:
    image: mysql
    container_name: fvn-loans-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loans-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  cards-db:
    image: mysql
    container_name: fvn-cards-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cards-db
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: rabbitmq:3.13-management
    container_name: fvn-rabbitmq-ms
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: devmayank8/finvistanexus-configserver:2.2.0-SNAPSHOT
    container_name: fvn-configserver-ms
    ports:
      - "8071:8071" #MAIN
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: devmayank8/finvistanexus-accounts:2.2.0-SNAPSHOT
    container_name: fvn-accounts-ms
    ports:
      - "8080:8080" #MAIN
      - "5005:5005" #DEBUG
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:mysql://accounts-db:3306/accounts-db
    depends_on:
      configserver:
        condition: service_healthy
      accounts-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loans:
    image: devmayank8/finvistanexus-loans:2.2.0-SNAPSHOT
    container_name: fvn-loans-ms
    ports:
      - "8090:8090" #MAIN
      - "5010:5010" #DEBUG
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: jdbc:mysql://loans-db:3306/loans-db
    depends_on:
      configserver:
        condition: service_healthy
      loans-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: devmayank8/finvistanexus-cards:2.2.0-SNAPSHOT
    container_name: fvn-cards-ms
    ports:
      - "9000:9000" #MAIN
      - "5015:5015" #DEBUG
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: jdbc:mysql://cards-db:3306/cards-db
    depends_on:
      configserver:
        condition: service_healthy
      cards-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  fvn-network:
    driver: "bridge"