version: '3.9'

services:
  rabbit:
    image: rabbitmq:3.13-management
    container_name: fvn-rabbitmq-ms
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: devmayank8/finvistanexus-configserver:3.0.0-SNAPSHOT
    container_name: fvn-configserver-ms
    ports:
      - "8071:8071" #MAIN
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: devmayank8/finvistanexus-accounts:3.0.0-SNAPSHOT
    container_name: fvn-accounts-ms
    ports:
      - "8080:8080" #MAIN
      - "5005:5005" #DEBUG
    environment:
      SPRING_APPLICATION_NAME: accounts
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loans:
    image: devmayank8/finvistanexus-loans:3.0.0-SNAPSHOT
    container_name: fvn-loans-ms
    ports:
      - "8090:8090" #MAIN
      - "5010:5010" #DEBUG
    environment:
      SPRING_APPLICATION_NAME: loans
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: devmayank8/finvistanexus-cards:3.0.0-SNAPSHOT
    container_name: fvn-cards-ms
    ports:
      - "9000:9000" #MAIN
      - "5015:5015" #DEBUG
    environment:
      SPRING_APPLICATION_NAME: cards
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  fvn-network:
    driver: "bridge"