server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///E://Coding//fvn-config"
        git:
          uri: "https://github.com/MayankGupta-dev08/fvn-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


encrypt:
  key: "u2ZY4UkzZfhcC1dUx/PD1ZEpFv2XuPmdOzGI/7nlnXY="