server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///E://Coding//fvn-config"
        git:
          uri: "https://github.com/MayankGupta-dev08/fvn-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


# key is mentioned here, but in case of actual business app,
# it will be passed as environment variable and
# the config server will be deployed behind the firewall of the company.
encrypt:
  key: "u2ZY4UkzZfhcC1dUx/PD1ZEpFv2XuPmdOzGI/7nlnXY="


logging:
  level:
    dev:
      mayankg:
        configserver: DEBUG