server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0: #binding name according to functions (email|sms)
          destination: send-communication #queueName
          group: ${spring.application.name}
        emailsms-out-0: #binding name according to functions (email|sms)
          destination: communication-sent #exhange name for outgoing msg
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s